version: '3.8'

services:
  num-webapp:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    stdin_open: true
    tty: true
    restart: unless-stopped
